version: 2
updates:
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/web"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
